/* SolPrep — Content Data */
const MODULES=[
{id:'solana-fund',title:'Solana Fundamentals',short:'Fundamentals',icon:'⚡',level:'Beginner → Mid',desc:'Master Proof of History, Sealevel runtime, account model, rent, Gulf Stream, and Tower BFT.',topics:[
{id:'poh',title:'Proof of History (PoH)',content:'PoH is a <strong>Verifiable Delay Function (VDF)</strong> using continuous recursive SHA-256 hashing. It creates a cryptographic clock that timestamps transactions without global clock synchronization. Each hash output becomes the next input — provably sequential. This eliminates inter-validator messaging overhead, enabling ~400ms slot times. Tower BFT leverages PoH timestamps to finalize consensus faster.',code:'// PoH conceptual model\nlet hash = sha256(prev_hash + counter);\n// Each iteration is one "tick"\n// Count encodes elapsed time in CPU cycles\n// Validators trust the VDF chain — no clock sync needed'},
{id:'accounts',title:'Account Model & Data Storage',content:'In Solana, <strong>everything is an account</strong>. Programs are stateless — state lives in separate data accounts. Program accounts store executable code, data accounts store state (owned by programs), wallet accounts hold SOL. This separation enables Sealevel\'s parallel execution since transactions declare which accounts they access.',code:'// Account structure\npub struct Account {\n    pub lamports: u64,      // Balance\n    pub data: Vec<u8>,       // Arbitrary data\n    pub owner: Pubkey,       // Owning program\n    pub executable: bool,    // Is this a program?\n    pub rent_epoch: u64,     // Rent tracking\n}'},
{id:'sealevel',title:'Sealevel: Parallel Execution',content:'Sealevel is Solana\'s parallel smart-contract runtime. Transactions must <strong>declare all accounts they read/write before execution</strong>. The scheduler groups transactions by account sets and runs non-conflicting ones concurrently across CPU cores. Transactions sharing writable accounts are serialized. This creates hot-account bottlenecks (e.g., popular AMM pools).',code:'// Transaction specifies accounts upfront\nlet tx = Transaction::new_with_payer(\n    &[instruction],\n    Some(&payer.pubkey()),\n);\n// Runtime checks: disjoint write sets → parallel\n// Overlapping write sets → sequential'},
{id:'rent',title:'Rent Exemption & Account Lifecycle',content:'Accounts must hold minimum SOL proportional to data size (~0.00203 SOL per 128 bytes) to be <strong>rent-exempt</strong>. Accounts below threshold are garbage collected. Closing accounts returns lamports to payer and zeros data. Failure to zero data enables Revival Attacks.',code:'// Anchor: closing an account properly\n#[account(\n    mut,\n    close = user  // transfers lamports, zeroes data\n)]\npub data_account: Account<\'info, MyData>,'},
{id:'gulf',title:'Gulf Stream & Transaction Forwarding',content:'Gulf Stream is Solana\'s mempool-less transaction forwarding protocol. Since the leader schedule is known in advance via PoH, clients forward transactions directly to the upcoming leader. This enables pre-processing before slot begins, reduces unconfirmed tx memory, and achieves ~400ms optimistic confirmation. Downside: transactions to wrong/skipped leaders may expire.'},
]},
{id:'rust',title:'Rust for Solana',short:'Rust',icon:'🦀',level:'Beginner → Mid',desc:'Deep dive into ownership, borrowing, lifetimes, error handling, traits, and memory safety for on-chain programs.',topics:[
{id:'ownership',title:'Ownership & Borrowing',content:'Rust enforces three ownership rules at <strong>compile time</strong>: every value has exactly one owner, values are dropped when owner goes out of scope, and borrowing allows temporary access. This gives zero-cost memory safety — no GC pauses (critical for 400ms slots). The borrow checker prevents data races.',code:'// Ownership transfer (move)\nlet s1 = String::from("solana");\nlet s2 = s1;  // s1 moved, now invalid\n\n// Borrowing (reference)\nfn print_len(s: &String) {\n    println!("{}", s.len());  // borrows, no move\n}\nlet s3 = String::from("anchor");\nprint_len(&s3);  // s3 still valid'},
{id:'lifetimes',title:'Lifetimes in Solana Context',content:'Lifetimes track how long references remain valid. In Solana, the <strong>AccountInfo<\'info></strong> struct borrows from the transaction context — its lifetime must not outlive the transaction. Anchor\'s Context struct ties all account lifetimes together. Attempting to hold data references beyond instruction scope causes compile errors.',code:'// AccountInfo borrows from transaction context\npub struct AccountInfo<\'info> {\n    pub key: &\'info Pubkey,\n    pub lamports: Rc<RefCell<&\'info mut u64>>,\n    pub data: Rc<RefCell<&\'info mut [u8]>>,\n    pub owner: &\'info Pubkey,\n}'},
{id:'errors',title:'Error Handling (Result & Option)',content:'Rust uses <strong>Result&lt;T,E&gt;</strong> and <strong>Option&lt;T&gt;</strong> instead of exceptions. Every fallible function returns Result. The ? operator propagates errors with zero runtime cost. In Solana programs, use custom error enums with #[error_code] for meaningful error messages.',code:'// Solana error handling\n#[error_code]\npub enum MyError {\n    #[msg("Insufficient funds for withdrawal")]\n    InsufficientFunds,\n    #[msg("Invalid authority")]\n    InvalidAuthority,\n}\n\npub fn withdraw(ctx: Context<Withdraw>, amount: u64) -> Result<()> {\n    require!(ctx.accounts.vault.amount >= amount, \n             MyError::InsufficientFunds);\n    Ok(())\n}'},
{id:'traits',title:'Traits, Generics & Smart Pointers',content:'Traits define shared behavior. <strong>Box&lt;T&gt;</strong> = heap allocation with single ownership. <strong>Rc&lt;T&gt;</strong> = reference-counted for single-threaded (used in AccountInfo). <strong>Arc&lt;T&gt;</strong> = atomic ref count for multi-threaded (validator internals). In on-chain code, Rc<RefCell<>> is used for shared mutable access within transactions.'},
]},
{id:'anchor',title:'Anchor Framework',short:'Anchor',icon:'⚓',level:'Mid → Advanced',desc:'Master the industry-standard Solana framework: macros, PDAs, CPI contexts, constraints, and IDL generation.',topics:[
{id:'derive',title:'#[derive(Accounts)] Macro',content:'Anchor uses #[derive(Accounts)] to define expected accounts for each instruction. It auto-generates serialization, security checks, and IDL. Constraints like <strong>has_one</strong>, <strong>signer</strong>, and <strong>mut</strong> enforce the Principle of Least Privilege. Missing signer checks allow attackers to execute operations for arbitrary keys.',code:'#[derive(Accounts)]\npub struct Initialize<\'info> {\n    #[account(\n        init,\n        payer = user,\n        space = 8 + 32 + 8,  // discriminator + pubkey + u64\n    )]\n    pub data_account: Account<\'info, MyData>,\n    #[account(mut)]\n    pub user: Signer<\'info>,\n    pub system_program: Program<\'info, System>,\n}'},
{id:'pdas',title:'Program Derived Addresses (PDAs)',content:'PDAs are deterministic addresses derived from program ID and seeds that do NOT lie on the ed25519 curve — no private key can sign for them. Only the program can sign via invoke_signed(). Use cases: trustless escrow, vaults, per-user accounts. <strong>Always cache bump seeds</strong> in state accounts to avoid recomputation (saves thousands of CUs).',code:'// PDA with Anchor\n#[account(\n    init,\n    payer = user,\n    space = 8 + Vault::LEN,\n    seeds = [b"vault", user.key().as_ref()],\n    bump\n)]\npub vault: Account<\'info, Vault>,\n\n// Cache the bump!\n#[account]\npub struct Vault {\n    pub authority: Pubkey,\n    pub amount: u64,\n    pub bump: u8,  // cached for future CPIs\n}'},
{id:'cpi',title:'Cross-Program Invocations (CPI)',content:'CPI enables programs to call other programs. Anchor provides CpiContext for type-safe invocations. CPI depth is capped at 4 levels. For PDA-signed CPIs, use signer seeds with cached bump. Always validate program IDs to prevent confused deputy attacks.',code:'// CPI: Transfer SOL using system_program\nlet cpi_ctx = CpiContext::new(\n    ctx.accounts.system_program.to_account_info(),\n    Transfer {\n        from: ctx.accounts.from.to_account_info(),\n        to: ctx.accounts.to.to_account_info(),\n    },\n);\ntransfer(cpi_ctx, amount)?;'},
{id:'remaining',title:'Dynamic Accounts (remaining_accounts)',content:'When required accounts aren\'t known at compile time, use <strong>remaining_accounts</strong> in the Anchor context. Manually deserialize and validate each account. Useful for variable-length operations like batch processing or dynamic token lists.'},
]},
{id:'security',title:'Smart Contract Security',short:'Security',icon:'🛡️',level:'Advanced',desc:'Identify and mitigate Revival Attacks, CPI depth exhaustion, integer overflows, confused deputy, and PDA collisions.',topics:[
{id:'revival',title:'Revival Attack',content:'When closing an account, lamports are transferred out. But an attacker can append an instruction in the SAME transaction to transfer lamports BACK, keeping the account alive. The program\'s subsequent logic assumes it\'s closed — enabling double refunds or vault manipulation. <strong>Mitigation:</strong> Zero out data buffer AND alter discriminator during closure.',code:'// Vulnerable: just draining lamports\n**ctx.accounts.target.to_account_info().lamports.borrow_mut() = 0;\n\n// Secure: Anchor\'s close constraint handles this\n#[account(\n    mut,\n    close = authority,  // zeros data + transfers lamports\n    has_one = authority,\n)]\npub target: Account<\'info, MyData>,'},
{id:'cpi-depth',title:'CPI Depth Exhaustion',content:'Solana caps CPI depth at 4 levels. Attackers can construct transactions that approach this limit before calling your program, forcing internal CPIs to fail. Devastating for interdependent DeFi protocols. <strong>Mitigation:</strong> Design asynchronous state machines, avoid deep synchronous callbacks, limit Transfer Hooks in Token-2022.'},
{id:'integer',title:'Integer Safety',content:'Rust release builds can enable wrapping arithmetic. Always use <strong>checked_add</strong>, <strong>checked_sub</strong>, <strong>checked_mul</strong> or Anchor\'s require! macro. Underflow bugs (subtracting more than available) are common exploit vectors.',code:'// UNSAFE\nlet result = balance - withdrawal; // can underflow!\n\n// SAFE\nlet result = balance\n    .checked_sub(withdrawal)\n    .ok_or(MyError::InsufficientFunds)?;'},
{id:'confused',title:'Confused Deputy Problem',content:'When your program forwards a signer account to another program via CPI without checking it, that other program could misuse the authority. <strong>Always validate</strong> that account owners, program IDs, and signer authorities match expected values.'},
{id:'pda-collisions',title:'PDA Seed Collisions',content:'If PDA seeds aren\'t unique enough, different logical accounts can derive to the same address, creating DoS or data corruption. <strong>Best practice:</strong> Use constant prefixes + unique data (user pubkey, counter) as seeds. Zellic warns PDA seed collisions are a top vulnerability.'},
]},
{id:'sysdesign',title:'System Design',short:'Sys Design',icon:'🏛️',level:'Senior',desc:'Architect prediction markets, DEX orderbooks, sharding strategies, and off-chain indexing infrastructure.',topics:[
{id:'prediction',title:'Prediction Market Design',content:'Map relational concepts into flat accounts. <strong>Events → Outcomes → Bets</strong> as hierarchical PDAs. Never store user arrays in Outcome accounts (10MB limit, compute exhaustion). Use individual Bet accounts per user with running totals in Outcome. Payout = (win_pool × user_bet) / total_winning_bets — constant time O(1) operation.',code:'// Account hierarchy\n// Event PDA: seeds = ["event", event_id]\n// Outcome PDA: seeds = ["outcome", event_key, outcome_idx]\n// Bet PDA: seeds = ["bet", outcome_key, user_key]\n\n#[account]\npub struct Outcome {\n    pub event: Pubkey,\n    pub index: u8,\n    pub total_bets: u64,  // Running invariant\n    pub resolved: bool,\n}'},
{id:'sharding',title:'Deterministic Sharding',content:'The most punishing bottleneck: write contention. When thousands of users hit the same account, Sealevel serializes all transactions. <strong>Solution:</strong> Initialize multiple shard accounts. Client SDK routes users to shards via modulo on their pubkey. This distributes write load across CPU cores. Async admin crank consolidates shards periodically.',code:'// Deterministic shard routing\nlet shard_idx = user_pubkey.to_bytes()[0] % NUM_SHARDS;\nlet shard_pda = find_program_address(\n    &[b"shard", &[shard_idx]],\n    program_id\n);'},
{id:'indexing',title:'Off-Chain Indexing (Yellowstone gRPC)',content:'Standard RPC is too slow and rate-limited for production UIs. <strong>Yellowstone gRPC</strong> streams raw account and block data with sub-100ms latency from validator plugins (Geyser). Ingest into a dedicated database for instant search, historical analytics, and complex aggregations without hitting public RPC.'},
]},
{id:'advanced',title:'Advanced Topics',short:'Advanced',icon:'🔬',level:'Senior',desc:'MEV & Jito Bundles, Firedancer client risks, ZK Compression, and cutting-edge 2026 ecosystem trends.',topics:[
{id:'mev',title:'MEV & Jito Bundles',content:'MEV on Solana was historically brute-force spam (58% of validator compute at peak). <strong>Jito Labs</strong> introduced a modified validator client + off-chain block engine. Searchers package trades into atomic bundles with tips. The block engine auctions bundle inclusion. This eliminated spam, ensured deterministic execution for DeFi arbitrage, and created staker revenue (~$720M annual). Senior devs must understand bundle construction and sandwich attack resistance.',code:'// Jito bundle construction (conceptual)\nconst bundle = [\n    tx1_swap_token_a_to_b,  // Atomic sequence\n    tx2_arb_profit,          // Guaranteed order\n];\n// Attach tip to block engine\nbundle.tip = 10_000; // lamports\njito.sendBundle(bundle);'},
{id:'firedancer',title:'Firedancer Client & Skip-Vote Risks',content:'Firedancer is an independent C validator client optimized for HFT latency, using custom SIMD instructions and bypassing kernel networking. It can process millions of TPS. <strong>Risk:</strong> Legacy validators may struggle with dense blocks within 400ms slots, causing skip-votes and micro-reorgs. Protocols must demand <strong>Finalized</strong> commitment (not Confirmed) for bridges, liquidations, and oracle updates.'},
{id:'zk',title:'ZK State Compression',content:'2026 scaling trend: store only Merkle roots on-chain, with full data off-chain. Dramatically reduces account rent costs. Used for scalable airdrops and NFT marketplaces. Developers write on-chain verifier programs that consume ZK proofs from clients — hybrid Web2/Web3 architecture.'},
]}
];
const QUESTIONS=[
// Solana Fundamentals
{id:'q1',module:'solana-fund',diff:'easy',q:'What is Proof of History (PoH) and how does it enable Solana\'s performance?',a:'PoH is a Verifiable Delay Function (VDF) using continuous recursive SHA-256 hashing. It creates a cryptographic clock enabling sub-second block times by eliminating inter-validator clock sync messaging. Tower BFT leverages PoH timestamps for faster consensus finalization.',code:'// Each hash is sequential and verifiable\nlet hash = sha256(prev_hash + counter);',mistakes:['Describing PoH as a consensus mechanism (it\'s a clock, not consensus)','Forgetting Tower BFT\'s role in actual consensus']},
{id:'q2',module:'solana-fund',diff:'easy',q:'Describe Solana\'s account model. How does it differ from Ethereum?',a:'Solana separates code (programs) from state (data accounts). Programs are stateless — all data passed via accounts. Each account has: lamports, data, owner, executable flag. Unlike Ethereum where contract storage is internal, Solana\'s separation enables Sealevel\'s parallel execution.',mistakes:['Confusing Solana accounts with Ethereum accounts','Not mentioning the parallelism benefit']},
{id:'q3',module:'solana-fund',diff:'medium',q:'What is a Program Derived Address (PDA)? When and why would you use one?',a:'A PDA is a deterministic address derived from program ID and seeds that does NOT lie on the ed25519 curve — no private key exists. Only the owning program can sign. Used for trustless vaults, escrow, per-user state accounts. Seeds provide deterministic, collision-free addressing.',code:'let (pda, bump) = Pubkey::find_program_address(\n    &[b"vault", user.key().as_ref()],\n    program_id\n);',mistakes:['Not explaining why PDAs are off-curve','Forgetting to cache bump seeds']},
{id:'q4',module:'solana-fund',diff:'senior',q:'How does Sealevel enable parallel transaction execution? What are its constraints?',a:'Sealevel requires transactions to pre-declare all read/write accounts. Non-conflicting transactions (disjoint account sets) execute concurrently across CPU cores. Shared writable accounts force serialization. Developers must minimize account overlap, use per-user accounts, and understand hot-account bottlenecks.',mistakes:['Not mentioning write contention implications','Forgetting CPI impact on parallelism']},
{id:'q5',module:'solana-fund',diff:'easy',q:'Explain rent exemption in Solana.',a:'Accounts must hold minimum SOL proportional to data size (~0.00203 SOL per 128 bytes) to be rent-exempt. Sub-threshold accounts are garbage collected. Closing accounts returns lamports. Failure to zero data during closure enables Revival Attacks.',mistakes:['Not knowing approximate rent costs','Missing the security angle of account closure']},
{id:'q6',module:'solana-fund',diff:'medium',q:'What is Gulf Stream?',a:'Gulf Stream is Solana\'s mempool-less transaction forwarding. Since the leader schedule is known via PoH, clients forward transactions directly to upcoming leaders, enabling pre-processing and ~400ms optimistic confirmation.',mistakes:['Saying Solana has a traditional mempool']},
{id:'q7',module:'solana-fund',diff:'medium',q:'What are Compute Units (CUs) and how do they affect program design?',a:'CUs are Solana\'s equivalent of gas, capped at ~1.4M per transaction. Exceeding causes immediate failure. Developers must minimize allocations, cache PDA bumps, use zero-copy deserialization for large accounts, and avoid deep CPI chains.',mistakes:['Conflating CUs with transaction fees']},
// Rust
{id:'q8',module:'rust',diff:'easy',q:'Explain Rust\'s ownership model and why it suits Solana.',a:'Every value has one owner. When owner goes out of scope, value is dropped (no GC). Borrowing allows temporary access. This gives zero-cost memory safety — critical for 400ms blockchain slots where GC pauses would be catastrophic.',mistakes:['Not connecting ownership to Solana\'s runtime constraints']},
{id:'q9',module:'rust',diff:'medium',q:'What are lifetimes in Rust? Give a Solana-relevant example.',a:'Lifetimes track reference validity, preventing dangling pointers. In Solana, AccountInfo<\'info> borrows from the transaction context — its lifetime must not outlive the instruction execution. Anchor\'s Context struct ties all account lifetimes together.',mistakes:['Not providing a concrete Solana example']},
{id:'q10',module:'rust',diff:'senior',q:'When is unsafe Rust acceptable in Solana programs?',a:'Unsafe is sometimes needed for zero-copy deserialization — casting raw byte slices to Rust structs via pointer arithmetic (e.g., bytemuck). This avoids Borsh deserialization overhead that exhausts CU limits on large accounts. Risks: buffer overflows, use-after-free, memory misalignment. Must be heavily audited.',mistakes:['Suggesting unsafe is always wrong','Not mentioning zero-copy use case']},
{id:'q11',module:'rust',diff:'medium',q:'How does Rust prevent data races?',a:'The borrow checker enforces: many immutable refs OR one mutable ref, never both. Sealevel mirrors this at runtime — multiple transactions can read an account, but only one can write (exclusive write lock).',mistakes:['Not connecting to Sealevel\'s locking model']},
{id:'q12',module:'rust',diff:'easy',q:'How does Rust error handling work?',a:'Rust uses Result<T,E> and Option<T> instead of exceptions. The ? operator propagates errors with zero runtime cost. In Anchor, use #[error_code] enums for meaningful program errors.',mistakes:['Mentioning try-catch (Rust doesn\'t have it)']},
{id:'q13',module:'rust',diff:'medium',q:'Explain Box, Rc, and Arc in Solana context.',a:'Box<T>: heap allocation, single owner (trait objects). Rc<T>: reference-counted, single-threaded (used in AccountInfo for shared lamport access). Arc<T>: atomic ref count, multi-threaded (validator internals only, not on-chain).',mistakes:['Suggesting Arc in on-chain code']},
// Anchor
{id:'q14',module:'anchor',diff:'easy',q:'What is Anchor and how does it simplify Solana development?',a:'Anchor is a Rust DSL providing account serialization, constraint enforcement, IDL generation, and TypeScript client generation. It uses #[derive(Accounts)] and #[account] macros to reduce boilerplate and auto-generate security checks.',mistakes:['Treating Anchor as a silver bullet — it has pitfalls like seed-order bugs']},
{id:'q15',module:'anchor',diff:'medium',q:'Explain how PDA derivation works in Anchor with seeds and bumps.',a:'Seeds are byte arrays used with the program ID to derive a deterministic address. Anchor\'s seeds = [...] constraint auto-derives and validates PDAs. The bump is the value that pushes the address off the ed25519 curve. Cache bumps in state accounts to save compute.',code:'#[account(\n    init,\n    seeds = [b"data", user.key().as_ref()],\n    bump,\n    payer = user,\n    space = 8 + DataAccount::LEN\n)]\npub data: Account<\'info, DataAccount>,',mistakes:['Misordering seeds (causes ConstraintSeeds error)','Not caching bump']},
{id:'q16',module:'anchor',diff:'hard',q:'How do you handle dynamic accounts with remaining_accounts?',a:'When required accounts aren\'t known at compile time, access ctx.remaining_accounts. Manually deserialize and validate each AccountInfo. Use for variable-length operations like processing multiple token accounts in a single transaction.',mistakes:['Not validating remaining accounts (security risk)']},
{id:'q17',module:'anchor',diff:'medium',q:'Explain CPI in Anchor with signer seeds.',a:'CPI allows calling other programs. Use CpiContext::new_with_signer for PDA-signed calls. Pass signer seeds (including cached bump) so the runtime can verify the PDA authority.',code:'let seeds = &[b"vault", user.key.as_ref(), &[vault.bump]];\nlet signer = &[&seeds[..]];\nlet cpi_ctx = CpiContext::new_with_signer(\n    token_program.to_account_info(),\n    Transfer { from: vault_ata, to: user_ata, authority: vault },\n    signer\n);\ntransfer(cpi_ctx, amount)?;',mistakes:['Forgetting signer seeds for PDA authority']},
// Security
{id:'q18',module:'security',diff:'senior',q:'What is a Revival Attack and how do you mitigate it?',a:'When closing an account, an attacker appends an instruction in the same transaction to re-fund it with lamports, preventing garbage collection. The "closed" account persists with potentially exploitable state. Mitigation: zero out data buffer AND alter discriminator. Anchor\'s close constraint handles this.',mistakes:['Only draining lamports without zeroing data']},
{id:'q19',module:'security',diff:'hard',q:'How does CPI depth exhaustion work as an attack vector?',a:'Solana caps CPI at 4 levels deep. Attacker constructs transactions that reach depth 3 before calling victim protocol, causing the victim\'s internal CPIs to fail. Devastating for interdependent DeFi. Mitigation: avoid deep synchronous callbacks, use async state machines.',mistakes:['Not knowing the 4-level CPI limit']},
{id:'q20',module:'security',diff:'medium',q:'How do you prevent integer overflow in Solana programs?',a:'Use checked_add, checked_sub, checked_mul, checked_div. Rust release builds may enable wrapping arithmetic. Anchor\'s require! macro adds bounds checking. Always validate arithmetic before state mutations.',mistakes:['Relying on debug mode overflow checks in production']},
{id:'q21',module:'security',diff:'hard',q:'Explain the Confused Deputy problem in Solana.',a:'If your program forwards a signer account to another program via CPI without validating it, the called program could misuse the authority. Always verify account owners, program IDs, and that signer authorities match expected values before CPI.',mistakes:['Not validating program IDs in CPI calls']},
{id:'q22',module:'security',diff:'medium',q:'What are PDA seed collision risks?',a:'If seeds aren\'t unique enough, different logical accounts derive to the same address, causing DoS or data corruption. Use constant prefixes plus unique data (user pubkey, numeric IDs) as seeds.',mistakes:['Using only static strings as PDA seeds']},
{id:'q23',module:'security',diff:'medium',q:'Why must you reload accounts after CPI?',a:'After a CPI, account data may be stale in your program. Call Anchor\'s reload() on accounts so Rust struct fields reflect the updated state from the called program.',mistakes:['Using stale data after CPI for subsequent logic']},
// System Design  
{id:'q24',module:'sysdesign',diff:'senior',q:'Design a decentralized prediction market on Solana.',a:'Hierarchical PDAs: Event (root, holds oracle + pool), Outcome (derived from Event + index, stores total_bets), Bet (per-user, derived from Outcome + user). Never use arrays for participants (10MB limit). Running invariant: total wagered per outcome. Payout is O(1): (win_pool × user_bet) / total_winning_bets.',mistakes:['Storing all bets in a single array','Making payout O(n) instead of O(1)']},
{id:'q25',module:'sysdesign',diff:'senior',q:'How do you resolve write contention at scale?',a:'Deterministic sharding. Initialize N shard accounts. Client SDK routes users via pubkey modulo N. Distributes write load across CPU cores. Async admin crank periodically consolidates shards into master state.',mistakes:['Using a single global state account for high-throughput protocols']},
{id:'q26',module:'sysdesign',diff:'hard',q:'Design an off-chain indexing architecture for a Solana DApp.',a:'Use Yellowstone gRPC (Geyser plugin) to stream account and block data with sub-100ms latency. Ingest into PostgreSQL or ClickHouse. Build REST/GraphQL API layer. This avoids rate-limited public RPC and enables historical analytics, search, and complex aggregations.',mistakes:['Relying solely on public RPC for production apps']},
// Advanced
{id:'q27',module:'advanced',diff:'senior',q:'How does Jito\'s MEV infrastructure work on Solana?',a:'Searchers package trades into atomic bundles with deterministic ordering. Jito block engine simulates profitability, auctions bundle inclusion via tips. Validators earn extra revenue. This replaced network spam (was 58% of compute). Bundles guarantee execution order, enabling DeFi arbitrage without probabilistic spamming.',mistakes:['Not understanding bundle atomicity','Ignoring sandwich attack risks from deterministic ordering']},
{id:'q28',module:'advanced',diff:'senior',q:'What risks does Firedancer introduce?',a:'Firedancer produces massive blocks that legacy validators may not process within 400ms slots. These validators skip-vote, causing micro-reorganizations. Protocols must use Finalized commitment (not Confirmed) for high-value ops. Implement slippage tolerances and valid-until-slot checks.',mistakes:['Assuming instant finality','Using Confirmed commitment for bridge withdrawals']},
{id:'q29',module:'advanced',diff:'hard',q:'What is ZK State Compression and why does it matter?',a:'Store only Merkle roots on-chain, with full data off-chain in databases. Drastically reduces account rent costs. Used for scalable airdrops, NFT marketplaces. On-chain verifier programs consume ZK proofs from clients. Enables hybrid Web2/Web3 architectures.',mistakes:['Not understanding the on-chain/off-chain split']},
{id:'q30',module:'advanced',diff:'medium',q:'What is zero-copy deserialization and when should you use it?',a:'Standard Borsh deserialization allocates new memory, exhausting CUs for large accounts. Zero-copy (via bytemuck) casts raw byte slices directly to Rust structs with pointer arithmetic — negligible compute overhead. Use for accounts >10KB like order books or pricing arrays.',code:'// Zero-copy account in Anchor\n#[account(zero_copy)]\npub struct BigAccount {\n    pub data: [u64; 1000],\n}',mistakes:['Using Borsh for accounts larger than 10KB']},
];
const CHALLENGES=[
{title:'Escrow Program',diff:'senior',desc:'Build a secure escrow: Maker deposits Token A, Taker exchanges Token B. Must handle make, take, and refund instructions with PDA-controlled vault.',starter:'use anchor_lang::prelude::*;\n\ndeclare_id!("YOUR_PROGRAM_ID");\n\n#[program]\nmod escrow {\n    use super::*;\n    \n    pub fn make(ctx: Context<Make>, amount: u64, receive_amount: u64) -> Result<()> {\n        // TODO: Transfer Token A to vault\n        // TODO: Store escrow state\n        Ok(())\n    }\n    \n    pub fn take(ctx: Context<Take>) -> Result<()> {\n        // TODO: Verify and execute exchange\n        Ok(())\n    }\n}',hints:['Vault authority should be a PDA, not a keypair','Cache the PDA bump in the escrow state account','Use Checks-Effects-Interactions pattern in take()'],solution:'#[program]\nmod escrow {\n    use super::*;\n    \n    pub fn make(ctx: Context<Make>, seed: u64, deposit: u64, receive: u64) -> Result<()> {\n        ctx.accounts.escrow.set_inner(Escrow {\n            maker: ctx.accounts.maker.key(),\n            mint_a: ctx.accounts.mint_a.key(),\n            mint_b: ctx.accounts.mint_b.key(),\n            receive_amount: receive,\n            seed,\n            bump: ctx.bumps.escrow,\n        });\n        // Transfer Token A to vault\n        transfer_checked(\n            CpiContext::new(ctx.accounts.token_program.to_account_info(),\n                TransferChecked {\n                    from: ctx.accounts.maker_ata_a.to_account_info(),\n                    to: ctx.accounts.vault.to_account_info(),\n                    mint: ctx.accounts.mint_a.to_account_info(),\n                    authority: ctx.accounts.maker.to_account_info(),\n                }\n            ), deposit, ctx.accounts.mint_a.decimals\n        )?;\n        Ok(())\n    }\n}',walkthrough:'The make instruction: (1) Store escrow terms including cached bump, (2) Transfer Token A from maker to PDA-controlled vault. The take instruction: (1) Verify Taker sends correct Token B amount to Maker, (2) Release Token A from vault using PDA signer seeds, (3) Close escrow account. Refund: Maker reclaims via same PDA signer seeds.'},
{title:'PDA Counter',diff:'easy',desc:'Implement a global counter stored in a PDA that increments each time it\'s called.',starter:'use anchor_lang::prelude::*;\n\ndeclare_id!("YOUR_ID");\n\n#[program]\nmod counter {\n    use super::*;\n    \n    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {\n        // TODO\n        Ok(())\n    }\n    \n    pub fn increment(ctx: Context<Increment>) -> Result<()> {\n        // TODO\n        Ok(())\n    }\n}',hints:['Use seeds = [b"counter"] for the PDA','Use checked_add to prevent overflow'],solution:'#[program]\nmod counter {\n    use super::*;\n    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {\n        ctx.accounts.counter.count = 0;\n        ctx.accounts.counter.bump = ctx.bumps.counter;\n        Ok(())\n    }\n    pub fn increment(ctx: Context<Increment>) -> Result<()> {\n        ctx.accounts.counter.count = ctx.accounts.counter.count\n            .checked_add(1).unwrap();\n        Ok(())\n    }\n}\n\n#[derive(Accounts)]\npub struct Initialize<\'info> {\n    #[account(init, seeds=[b"counter"], bump, payer=user, space=8+8+1)]\n    pub counter: Account<\'info, Counter>,\n    #[account(mut)]\n    pub user: Signer<\'info>,\n    pub system_program: Program<\'info, System>,\n}\n\n#[account]\npub struct Counter { pub count: u64, pub bump: u8 }',walkthrough:'Initialize creates a PDA with seeds ["counter"]. The counter starts at 0 with cached bump. Increment uses checked_add for overflow safety. Both instructions reference the same PDA.'},
{title:'Token Minting CPI',diff:'medium',desc:'Write an Anchor instruction that mints SPL tokens to a user via CPI.',starter:'pub fn mint_to_user(ctx: Context<MintToUser>, amount: u64) -> Result<()> {\n    // TODO: CPI to SPL token program\n    Ok(())\n}',hints:['Use anchor_spl::token::mint_to','The mint authority must be a signer'],solution:'#[derive(Accounts)]\npub struct MintToUser<\'info> {\n    #[account(mut, has_one = mint_authority)]\n    pub mint: Account<\'info, Mint>,\n    #[account(mut)]\n    pub user_token_account: Account<\'info, TokenAccount>,\n    pub mint_authority: Signer<\'info>,\n    pub token_program: Program<\'info, Token>,\n}\n\npub fn mint_to_user(ctx: Context<MintToUser>, amount: u64) -> Result<()> {\n    let cpi_accounts = MintTo {\n        mint: ctx.accounts.mint.to_account_info(),\n        to: ctx.accounts.user_token_account.to_account_info(),\n        authority: ctx.accounts.mint_authority.to_account_info(),\n    };\n    let cpi_ctx = CpiContext::new(\n        ctx.accounts.token_program.to_account_info(),\n        cpi_accounts\n    );\n    anchor_spl::token::mint_to(cpi_ctx, amount)?;\n    Ok(())\n}',walkthrough:'Define accounts: mutable mint (with has_one for authority), user token account, signer authority, and token program. Create CpiContext with the token program and MintTo accounts. Call mint_to with amount.'},
{title:'Debug: Seed Mismatch',diff:'medium',desc:'Find the bug: This program fails with ConstraintSeeds error. The client derives PDA with [b"data", b"user1"] but the program uses different seeds.',starter:'// BUG: Client uses [b"data", b"user1"]\n// But program has:\n#[account(\n    seeds = [b"data1", b"user1"],\n    bump\n)]\npub data: Account<\'info, MyData>,',hints:['Compare the seed arrays character by character','The client uses "data" but program uses "data1"'],solution:'// FIX: Make seeds match!\n// Either change client:\nconst [pda] = PublicKey.findProgramAddressSync(\n    [Buffer.from("data1"), Buffer.from("user1")],\n    programId\n);\n\n// Or change program:\n#[account(\n    seeds = [b"data", b"user1"],  // match client\n    bump\n)]\npub data: Account<\'info, MyData>,',walkthrough:'The bug is a seed mismatch: client derives with "data" but program expects "data1". PDAs are deterministic — even one character difference produces a completely different address. Always ensure client and program seeds match exactly.'},
{title:'Prevent Revival Attack',diff:'hard',desc:'This account closure is vulnerable to revival attacks. Fix it to properly prevent account resurrection.',starter:'pub fn close_account(ctx: Context<CloseAccount>) -> Result<()> {\n    // Vulnerable: only drains lamports\n    let dest = ctx.accounts.authority.to_account_info();\n    let source = ctx.accounts.target.to_account_info();\n    \n    **dest.lamports.borrow_mut() += source.lamports();\n    **source.lamports.borrow_mut() = 0;\n    \n    Ok(())\n}',hints:['Just draining lamports isn\'t enough','You need to zero the data AND change the discriminator','Anchor has a built-in close constraint'],solution:'// SECURE: Use Anchor\'s close constraint\n#[derive(Accounts)]\npub struct CloseAccount<\'info> {\n    #[account(\n        mut,\n        close = authority,  // Anchor handles:\n        // 1. Transfer all lamports to authority\n        // 2. Zero out account data\n        // 3. Set discriminator to CLOSED\n        has_one = authority,\n    )]\n    pub target: Account<\'info, MyData>,\n    #[account(mut)]\n    pub authority: Signer<\'info>,\n}\n\n// If manual: zero data + set discriminator\n// source.data.borrow_mut().fill(0);\n// source.data.borrow_mut()[..8].copy_from_slice(&CLOSED_DISCRIMINATOR);',walkthrough:'The vulnerability: an attacker re-funds the account in the same transaction. Even with 0 lamports, the account isn\'t garbage collected until after the transaction. If data isn\'t zeroed, subsequent instructions can read "valid" state. Fix: Anchor\'s close constraint transfers lamports, zeros all data, and sets a CLOSED discriminator.'},
{title:'Compute Optimization',diff:'hard',desc:'Optimize this inefficient code that wastes CUs on PDA derivation and unnecessary allocations.',starter:'pub fn process(ctx: Context<Process>) -> Result<()> {\n    // INEFFICIENT: Deriving PDA on-chain every call\n    let (pda, bump) = Pubkey::find_program_address(\n        &[b"vault", ctx.accounts.user.key.as_ref()],\n        ctx.program_id,\n    );\n    \n    // INEFFICIENT: Division in loop\n    for i in 0..100 {\n        let share = total_amount / num_participants;\n        // process each share...\n    }\n    \n    Ok(())\n}',hints:['Cache the PDA bump in the state account','Move invariant calculations outside the loop','Consider using bitwise shifts for powers of 2'],solution:'pub fn process(ctx: Context<Process>) -> Result<()> {\n    // OPTIMIZED: Use cached bump from state\n    let bump = ctx.accounts.vault.bump; // stored during init\n    \n    // OPTIMIZED: Calculate once outside loop\n    let share = total_amount\n        .checked_div(num_participants)\n        .ok_or(MyError::DivByZero)?;\n    \n    for i in 0..100 {\n        // Use pre-calculated share\n        // process_share(share);\n    }\n    \n    // BONUS: Use bitwise shift for powers of 2\n    let half = amount >> 1;  // instead of amount / 2\n    \n    Ok(())\n}',walkthrough:'Three optimizations: (1) Cache PDA bump during init — find_program_address costs thousands of CUs due to recursive hashing. (2) Hoist loop-invariant division outside the loop. (3) Use bitwise shift for power-of-2 division. Together these save potentially tens of thousands of CUs.'}
];
const FLASHCARDS=[
{cat:'Fundamentals',q:'What is Proof of History?',a:'A Verifiable Delay Function (VDF) using recursive SHA-256 hashing that serves as a cryptographic clock, eliminating inter-validator clock sync and enabling ~400ms slots.'},
{cat:'Fundamentals',q:'How does Sealevel enable parallelism?',a:'Transactions pre-declare all accounts they read/write. Non-conflicting transactions (disjoint account sets) run concurrently across CPU cores.'},
{cat:'Fundamentals',q:'What is rent exemption?',a:'Accounts must hold minimum SOL proportional to data size (~0.00203 SOL/128 bytes). Below threshold = garbage collected.'},
{cat:'Rust',q:'What are Rust\'s 3 ownership rules?',a:'1) Every value has exactly one owner. 2) When owner goes out of scope, value is dropped. 3) Borrowing allows temporary access without transfer.'},
{cat:'Rust',q:'What is the borrow checker rule?',a:'At any time: EITHER many immutable references OR one mutable reference — never both. This prevents data races at compile time.'},
{cat:'Rust',q:'Result<T,E> vs Option<T>?',a:'Result: for operations that can fail (Ok/Err). Option: for values that may not exist (Some/None). Both force explicit handling via pattern matching or ? operator.'},
{cat:'Anchor',q:'What does #[derive(Accounts)] do?',a:'Auto-generates account deserialization, constraint validation, and IDL definitions. Enforces security checks like signer verification and PDA derivation.'},
{cat:'Anchor',q:'What is a PDA bump?',a:'The u8 value that pushes a derived address off the ed25519 curve. Should be cached in state accounts to avoid expensive on-chain recomputation.'},
{cat:'Anchor',q:'CPI depth limit?',a:'4 levels maximum. Design async state machines to avoid deep synchronous callback chains.'},
{cat:'Security',q:'What is a Revival Attack?',a:'Attacker re-funds a "closed" account in the same transaction, keeping it alive. Mitigation: zero data buffer + alter discriminator during closure.'},
{cat:'Security',q:'Confused Deputy Problem?',a:'Forwarding signer authority to another program via CPI without validation. The called program could misuse the authority. Always verify program IDs and owners.'},
{cat:'Security',q:'checked_add vs + operator?',a:'checked_add returns None on overflow (safe). The + operator may wrap in release mode (unsafe). Always use checked arithmetic in on-chain code.'},
{cat:'Design',q:'How to solve write contention?',a:'Deterministic sharding: N shard accounts, route by user_pubkey % N. Distributes write load. Async crank consolidates state.'},
{cat:'Design',q:'Why not store arrays in accounts?',a:'10MB account limit + linear iteration exhausts CU budget. Use individual per-user accounts with running totals for O(1) operations.'},
{cat:'Advanced',q:'What are Jito Bundles?',a:'Atomic transaction sequences with deterministic ordering. Searchers tip for inclusion via off-chain auction. Replaced network spam, ensures execution order.'},
{cat:'Advanced',q:'Firedancer skip-vote risk?',a:'Dense Firedancer blocks may overwhelm legacy validators within 400ms slots. They skip-vote, causing micro-reorgs. Use Finalized commitment for critical ops.'},
];
const CHEATSHEETS=[
{title:'Anchor Account Constraints',content:'#[account(init)]          — Create new account\n#[account(mut)]           — Mark as mutable\n#[account(signer)]        — Require signature\n#[account(has_one = x)]   — Verify account.x == x.key()\n#[account(close = dest)]  — Close, send lamports to dest\n#[account(seeds = [..], bump)]  — PDA derivation\n#[account(zero_copy)]     — Zero-copy deserialization\n#[account(constraint = expr)]  — Custom constraint\n#[account(realloc = N, realloc::payer = p, realloc::zero = true)]'},
{title:'Solana Key Limits',content:'Account data max:       10 MB\nCompute Units per tx:   ~1.4M (1,400,000)\nCPI depth limit:        4 levels\nTransaction size:       1232 bytes\nSlot time:              ~400ms\nBlock time:             ~400ms\nFinality:               ~13 seconds\nBase tx fee:            5,000 lamports (~$0.00025)\n1 SOL = 1,000,000,000 lamports'},
{title:'Rust Quick Reference',content:'// Ownership\nlet s = String::from("hi"); // s owns the String\nlet s2 = s;                  // s moved to s2\nlet s3 = s2.clone();         // deep copy\n\n// Borrowing\nfn foo(s: &String) {}        // immutable borrow\nfn bar(s: &mut String) {}    // mutable borrow\n\n// Lifetimes\nfn longest<\'a>(x: &\'a str, y: &\'a str) -> &\'a str\n\n// Error handling\nlet result: Result<i32, Error> = Ok(42);\nlet value = result?;  // propagate error\n\n// Pattern matching\nmatch value {\n    Some(x) => println!("{}", x),\n    None => println!("empty"),\n}'},
{title:'Common PDA Patterns',content:'// Per-user account\nseeds = [b"user_data", user.key().as_ref()]\n\n// Per-user per-protocol\nseeds = [b"position", pool.key().as_ref(), user.key().as_ref()]\n\n// Global singleton\nseeds = [b"global_config"]\n\n// Indexed entries\nseeds = [b"entry", &entry_id.to_le_bytes()]\n\n// Multi-part with bump caching\n#[account]\npub struct MyPda {\n    pub data: u64,\n    pub bump: u8,  // ALWAYS cache bump\n}'},
{title:'Security Checklist',content:'□ All accounts validated (owner, signer, program)\n□ PDA seeds are unique and collision-free\n□ Bump seeds cached in state accounts\n□ checked_add/sub/mul for all arithmetic\n□ Account data zeroed on close (Revival Attack)\n□ CPI depth < 4 levels\n□ Program IDs validated in CPI calls\n□ Signer checks on all authority accounts\n□ Account reloaded after CPI\n□ Slippage tolerances for DeFi operations\n□ Use Finalized commitment for critical ops\n□ Transfer Hooks bounded (Token-2022)'},
];
const LASTDAY=[
{title:'⚡ Core Concepts to Review',points:['PoH = VDF (SHA-256 clock, not consensus)','Account model: code ≠ state (programs are stateless)','Sealevel: pre-declared accounts → parallel execution','PDA: off-curve address, program-only signing, cache bumps','CPI: max 4 depth, validate program IDs','Rent: ~0.00203 SOL / 128 bytes, close = zero data']},
{title:'🛡️ Security Must-Knows',points:['Revival Attack: re-funding closed accounts in same tx','Confused Deputy: unvalidated signer forwarding in CPI','Integer overflow: always use checked arithmetic','PDA collisions: use unique seed combinations','Account reload after CPI','Checks-Effects-Interactions pattern']},
{title:'🦀 Rust Key Points',points:['Ownership: one owner, drop on scope exit, no GC','Borrow checker: many &T OR one &mut T, never both','Lifetimes: AccountInfo<\'info> tied to transaction','Result<T,E> + ? operator for error propagation','Box (single owner) vs Rc (shared, single-thread) vs Arc (shared, multi-thread)']},
{title:'🎤 Behavioral Prep (STAR Method)',points:['Situation → Task → Action → Result','Have 3 stories ready: led complex project, security incident, system design tradeoff','Emphasize autonomy, ownership, cross-team communication','Mention: mainnet deployments, audit coordination, incident response','Show forward-thinking: MEV protection, Firedancer awareness, ZK trends']},
];
const MOCK_ROUNDS=[
{icon:'🦀',title:'Round 1: DSA + Rust',desc:'Basic algorithms and deep Rust knowledge. Ownership, lifetimes, error handling, concurrency.',duration:30,questions:[
{q:'Explain Rust\'s ownership model and give an example of a move vs clone.',ideal:'Every value has one owner. Assignment transfers ownership (move). clone() creates a deep copy. Moves are zero-cost; clones allocate memory. In Solana, moves prevent double-spending of account references.'},
{q:'What is the difference between &T, &mut T, and when would you use RefCell<T>?',ideal:'&T = shared immutable reference (many allowed). &mut T = exclusive mutable reference (one allowed). RefCell<T> = runtime borrow checking for interior mutability. Solana uses Rc<RefCell<&mut u64>> for AccountInfo.lamports to share mutable access within a transaction.',followUp:'Why does Solana use Rc<RefCell> instead of &mut for lamports?'},
{q:'How does Rust\'s error handling differ from exceptions? Show the ? operator.',ideal:'Rust uses Result<T,E> and Option<T> — no exceptions. The ? operator unwraps Ok/Some or returns the error to the caller. Zero runtime cost. Anchor programs use #[error_code] enums for custom errors.'},
{q:'Write a function that finds the most frequent element in a Vec<i32>.',ideal:'Use a HashMap to count occurrences, then find the max. Time: O(n), Space: O(n). In Solana context, minimize allocations — consider stack-based solutions for small inputs.'},
]},
{icon:'⚡',title:'Round 2: Solana Deep Dive',desc:'Architecture, Anchor, security, and on-chain program design. Expect code analysis.',duration:45,questions:[
{q:'Walk me through the lifecycle of a Solana transaction from submission to finality.',ideal:'Client submits to RPC → Gulf Stream forwards to upcoming leader → Leader timestamps via PoH → Sealevel checks account locks, executes in parallel → Block propagated via Turbine (erasure coding) → Validators vote via Tower BFT → Optimistic confirmation (~400ms) → Finalized confirmation (~13s, 31+ votes).'},
{q:'You\'re given an Anchor program that closes an account by draining lamports. Find the vulnerability and fix it.',ideal:'Revival Attack — attacker re-funds the account in the same transaction. Data persists, enabling double refunds. Fix: use Anchor\'s close constraint which zeros data buffer and alters discriminator.',followUp:'Can you show the code for a manual secure closure without Anchor\'s close?'},
{q:'Explain how you would implement an on-chain escrow using PDAs. Walk through the make and take instructions.',ideal:'Make: derive vault PDA from [b"escrow", maker_key, seed], transfer Token A to vault, store terms + cached bump in escrow state. Take: verify Taker sends correct Token B, use PDA signer seeds to release Token A from vault, close escrow. Refund: maker uses same signer seeds to reclaim.'},
{q:'A DeFi protocol\'s swap instruction sometimes fails with "compute budget exceeded." How do you debug and fix this?',ideal:'1) Use solana logs to find CU consumption. 2) Profile with sol_log_compute_units!(). 3) Common fixes: cache PDA bumps, use zero-copy for large accounts, hoist calculations outside loops, pre-compute off-chain, use bitwise ops for powers of 2. 4) Request higher CU budget via ComputeBudgetInstruction.',followUp:'What\'s the tradeoff of requesting higher compute budget?'},
{q:'What is the Revival Attack? Describe the attack vector and definitive mitigation.',ideal:'When closing an account, attacker appends an instruction in the same transaction to re-fund it with lamports. Account survives garbage collection with exploitable state. Mitigation: zero all data bytes AND set discriminator to CLOSED_ACCOUNT marker during closure instruction.'},
]},
{icon:'🏛️',title:'Round 3: System Design',desc:'Architect a protocol from scratch. Focus on account model, scalability, and security.',duration:45,questions:[
{q:'Design a decentralized prediction market on Solana. Cover accounts, scalability, and payout mechanism.',ideal:'Entity hierarchy: Event PDA → Outcome PDAs → individual Bet PDAs. Never use arrays for participants. Store running total_bets per outcome. Payout = (win_pool × user_bet) / total — O(1). Use oracle PDA for resolution. Deterministic sharding if >1000 concurrent bets.',followUp:'How would you handle oracle manipulation?'},
{q:'You need to build a highly concurrent DEX limit order book. How do you handle write contention?',ideal:'Deterministic sharding: N shard accounts, route orders by user_pubkey % N. Each shard maintains local order state. Matching engine runs as admin crank consolidating shards. Use Yellowstone gRPC for real-time UI updates. Consider cranked FIFO queues per price level.',followUp:'What happens if the crank goes down?'},
{q:'Architect an NFT marketplace using ZK State Compression for millions of NFTs.',ideal:'Store Merkle root on-chain, full tree off-chain in PostgreSQL. Mint = append leaf to tree + update root. Transfer = verify ZK proof of ownership + update root. Dramatically reduces rent costs. Use indexer (Helius DAS API) for off-chain queries. On-chain verifier program consumes proofs from client.'},
]}
];
const PROJECTS=[
{icon:'💰',title:'DeFi: Concentrated Liquidity AMM (CLAMM)',arch:'Inspired by Whirlpools/Uniswap V3. Liquidity concentrated in price ranges via tick-based positions. pool PDA → tick_array PDAs → position PDAs per user. Custom oracle for TWAP pricing. Flash loan resistance via callback verification.',accounts:'Program Accounts:\n├── Pool (global state, fee params, sqrt_price)\n├── TickArray[] (price range buckets, bitmap)\n├── Position[] (per-user, range + liquidity)\n├── Oracle (TWAP observations ring buffer)\n└── ProtocolFeeVault (PDA-controlled)',challenges:['Fixed-point arithmetic for tick math (Q64.64)','Efficient tick traversal during swaps','Token-2022 transfer hook integration','Flash loan callback verification','Oracle TWAP manipulation resistance'],talkingPoints:['Explain tick spacing optimization for CU efficiency','Discuss concentrated vs. full-range liquidity tradeoffs','Security: how you prevent sandwich attacks on swaps','Your approach to audit preparation and testing']},
{icon:'🖼️',title:'NFT Infrastructure: ZK-Compressed Marketplace',arch:'ZK State Compression for scalable NFT storage. Only Merkle roots on-chain. Full tree in PostgreSQL. On-chain verifier consumes proofs. Supports mint, transfer, list, and purchase with minimal rent.',accounts:'Program Accounts:\n├── MerkleTree (root hash, max depth, authority)\n├── Collection (metadata, royalty config)\n├── Listing[] (price, seller proof, expiry)\n├── Marketplace (fee %, treasury PDA)\n└── Off-chain: PostgreSQL (full tree, leaf data)',challenges:['Sparse Merkle tree management','ZK proof generation for ownership verification','Concurrent tree updates (multiple mints/transfers)','Royalty enforcement across compressed transfers','Indexing compressed state for frontend queries'],talkingPoints:['Cost comparison: standard NFTs vs compressed (1000x cheaper)','How you handle concurrent tree mutations','Off-chain indexer architecture (Helius DAS API)','Trade-offs of hybrid on-chain/off-chain design']},
{icon:'🏛️',title:'DAO Governance: Time-Locked Architecture',arch:'Multi-phase proposal lifecycle with cryptographic timelocks. Token-weighted voting with delegation. Multisig quorum for execution. Transparent upgrade authority controlled by DAO timelock.',accounts:'Program Accounts:\n├── DAO (config, treasury PDA, upgrade authority)\n├── Proposal[] (proposer, votes, status, eta)\n├── VoteRecord[] (per-user per-proposal)\n├── Timelock (delay config, queued txs)\n├── Treasury (PDA, multi-asset vault)\n└── Delegation[] (delegator → delegate mapping)',challenges:['Proposal lifecycle state machine (Draft→Active→Succeeded→Queued→Executed)','Time-locked execution with cryptographic proofs','Delegation without double-counting votes','Emergency circuit breaker (multisig pause)','Upgrade authority transfer to DAO timelock'],talkingPoints:['How you prevent governance attacks (flash loan voting)','Emergency pause mechanism design','Token delegation without lock-up','Upgrade authority management and trust minimization']},
];
